AWSTemplateFormatVersion: 2010-09-09
Description: On-Premise Template

Parameters:

  VPCIdentifier:
    Type: String
    Description: VPC Identifier
    Default: on-premise

  LatestAL2023AmiId:
    Description: Latest EC2 Amazon Linux 2023 AMI from Systems Manager Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'


Resources:

######################################
# NETWORK LAYER 
######################################


##################
# On Premise VPC
# Layer Type: Network Layer 
# Description:
# 
##################

  OnPremiseVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCIdentifier


##################
# Private Subnet 1
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - OnPremiseVPC
##################

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OnPremiseVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PrivateSubnet1


##################
# Public Subnet 1
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - OnPremiseVPC
##################

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OnPremiseVPC
      CidrBlock: 10.1.3.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PublicSubnet1






# Create AMI
#https://repost.aws/knowledge-center/ec2-systems-manager-ami-automation