AWSTemplateFormatVersion: 2010-09-09
Description: Public Cloud Project

Parameters:

  VPCIdentifier:
    Type: String
    Description: VPC Identifier
    Default: public-cloud

  


Resources:


##################
# Public Cloud VPC
# Layer Type: Network Layer 
# Description:
# 
##################

  PublicCloudVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCIdentifier

##################
# Public Cloud VPC
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#     -  
##################

  InternetGateWay:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Public Cloud VPC Internet Gateway

##################
# Public Cloud VPC
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#     -  
##################

  VPCtoIGWConnection:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateWay
      VpcId: !Ref PublicCloudVPC

##################
# Private Subnet 1
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - PublicCloudVPC
##################

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PublicCloudVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PrivateSubnet1

##################
# Private Subnet 2
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - PublicCloudVPC
##################

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PublicCloudVPC
      CidrBlock: 10.1.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PrivateSubnet2


##################
# Public Subnet 1
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - PublicCloudVPC
##################

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PublicCloudVPC
      CidrBlock: 10.1.3.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PublicSubnet1

##################
# Public Subnet 2
# Layer Type: Network Layer 
# Description:
# DependsOn: 
#   - PublicCloudVPC
##################

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PublicCloudVPC
      CidrBlock: 10.1.4.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PublicSubnet2



# Create AMI
#https://repost.aws/knowledge-center/ec2-systems-manager-ami-automation